## 1.3.1 Basic Operations on Images

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
def pltImage(img):
    plt.imshow(img)
    plt.xticks([]), plt.yticks([]) # to hide tick values on X and Y axis
    plt.show()

In [3]:
img = cv2.imread('i1.jpg')
px = img[100,100]
print(px)

[155 131 111]


In [4]:
pltImage(img)

In [5]:
blue = img[100,100,0]
print(blue)

155


In [6]:
img[100,100] = [255,255,255]
pltImage(img)

In [7]:
img.shape

(148, 339, 3)

In [8]:
img.size

150516

In [9]:
img.dtype

dtype('uint8')

In [10]:
w = 100
ball = img[280:340, 330:390]

In [11]:
pltImage(ball)

In [12]:
img[10:10+w, 10:10+w] = ball

In [13]:
pltImage(img)

In [14]:
b,g,r = cv2.split(img)

In [15]:
b.shape

(148, 339)

In [16]:
b

array([[143, 143, 143, ..., 116, 116, 116],
       [144, 144, 143, ..., 116, 116, 116],
       [144, 144, 144, ..., 116, 116, 116],
       ...,
       [114, 114, 113, ...,  75,  87, 103],
       [113, 113, 112, ..., 121, 135, 150],
       [112, 112, 111, ..., 167, 164, 159]], dtype=uint8)

In [17]:
g

array([[104, 104, 104, ...,  69,  69,  69],
       [105, 105, 104, ...,  69,  69,  69],
       [105, 105, 105, ...,  69,  69,  69],
       ...,
       [ 90,  90,  89, ...,  56,  68,  82],
       [ 89,  89,  88, ..., 104, 119, 131],
       [ 88,  88,  87, ..., 150, 148, 143]], dtype=uint8)

In [18]:
r

array([[ 66,  66,  66, ...,  37,  37,  37],
       [ 67,  67,  66, ...,  37,  37,  37],
       [ 67,  67,  67, ...,  37,  37,  37],
       ...,
       [ 72,  72,  71, ...,  43,  53,  67],
       [ 71,  71,  70, ...,  91, 103, 116],
       [ 70,  70,  69, ..., 137, 132, 127]], dtype=uint8)

In [19]:
img = cv2.merge((r,g,b))

In [20]:
pltImage(img)

In [21]:
pltImage(b)

In [22]:
pltImage(g)

In [23]:
pltImage(r)

In [24]:
BLUE = [255,0,0]
img1 = cv2.imread('opencv_logo.g')
m = 100
replicate = cv2.copyMakeBorder(img1,m,m,m,m,cv2.BORDER_REPLICATE)
reflect = cv2.copyMakeBorder(img1,m,m,m,m,cv2.BORDER_REFLECT)
reflect101 = cv2.copyMakeBorder(img1,m,m,m,m,cv2.BORDER_REFLECT_101)
wrap = cv2.copyMakeBorder(img1,m,m,m,m,cv2.BORDER_WRAP)
constant= cv2.copyMakeBorder(img1,m,m,m,m,cv2.BORDER_CONSTANT,value=BLUE)

In [25]:
plt.rcParams["figure.figsize"] = (20,10)
plt.subplot(231),plt.imshow(img1,'gray'),plt.title('ORIGINAL')
plt.subplot(232),plt.imshow(replicate,'gray'),plt.title('REPLICATE')
plt.subplot(233),plt.imshow(reflect,'gray'),plt.title('REFLECT')
plt.subplot(234),plt.imshow(reflect101,'gray'),plt.title('REFLECT_101')
plt.subplot(235),plt.imshow(wrap,'gray'),plt.title('WRAP')
plt.subplot(236),plt.imshow(constant,'gray'),plt.title('CONSTANT')
plt.show()