## 1.4.5 Morphological Transformations

In [15]:
import cv2
import numpy as np

In [16]:
img = cv2.imread('lena.png',0)
kernel = np.ones((5,5),np.uint8)
erosion = cv2.erode(img,kernel,iterations = 1)

In [17]:
dilation = cv2.dilate(img,kernel,iterations = 1)

In [18]:
opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)

In [19]:
closing = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)

In [20]:
gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel)

In [21]:
tophat = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, kernel)

In [22]:
blackhat = cv2.morphologyEx(img, cv2.MORPH_BLACKHAT, kernel)

In [23]:
cv2.getStructuringElement(cv2.MORPH_RECT,(5,5))
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

NameError: name 'array' is not defined

In [24]:
 cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
array([[0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0]], dtype=uint8)

NameError: name 'array' is not defined

In [25]:
cv2.getStructuringElement(cv2.MORPH_CROSS,(5,5))
array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=uint8)

NameError: name 'array' is not defined